/* Generated by the Nim Compiler v2.1.1 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var F = {procname: "module dom", prev: framePtr, filename: "/home/phil/.choosenim/toolchains/nim-#devel/lib/js/dom.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module dom", prev: framePtr, filename: "/home/phil/.choosenim/toolchains/nim-#devel/lib/js/dom.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module idk", prev: framePtr, filename: "/run/media/phil/StuffLmao/webdev/course-content/no-framework/test1/idk.nim", line: 0};
framePtr = F;
F.line = 5;
F.filename = "idk.nim";
window.alert("Hello world!");
framePtr = F.prev;
var F = {procname: "module idk", prev: framePtr, filename: "/run/media/phil/StuffLmao/webdev/course-content/no-framework/test1/idk.nim", line: 0};
framePtr = F;
framePtr = F.prev;
